## Assignment 2<br>MGMT 638: Data-Driven Investments: Equity<br>Rice University


::: {.callout-note appearance="minimal"}

## Instructions 

Submit an Excel workbook to Canvas.
:::

Open the file assignment2.xlsx in Excel.  It contains data on 100 tickers at 4 dates in January, 2023.

1.  Using the data for the first two dates (Jan 6 and Jan 13), run a linear regression of ret on pb and mom (including an intercept).

2.  Using the coefficients from the regression and the pb and mom data on the third date (Jan 20), compute predicted returns.

3.  Sort the stocks on Jan 20 on predicted returns.  Consider two portfolios: (i) the 20 stocks with the highest predicted returns and (ii) the 20 stocks with the lowest predicted returns.  Calculate the equally weighted portfolio returns for the week ending Jan 20 for each of these portfolios.

4.  Repeat 1-3, running the regression on the Jan 13 and Jan 20 data and computing predicted returns and portfolio returns for the Jan 27 data.

5. Average the portfolio returns over the two dates Jan 20 and Jan 27.  Did the stocks with the highest predicted returns beat the stocks with the lowest predicted returns?