## Data-Driven Investments: Equity<br>Rice University JGSB<br>Fall 2023


#### Instructor

[Kerry Back](http://kerryback.com)
<br>
J. Howard Creekmore Professor of Finance and Professor of Economics<br>
<a href="mailto:kerryback@gmail.com">kerryback@gmail.com</a>

#### Class Meeting

Room 317, 2:15 -- 3:45, 10/23/2023 -- 12/4/2023

#### Course Description   

This course provides an introduction to quantitative equity management.  Quantitative management means trading on signals that can be constructed and tested on large panels of stocks.  The basic elements are: return prediction, correlation prediction, portfolio optimization, and backtesting.  One form of quantitative investing is called factor investing or smart beta investing.  This has become increasingly popular.  For example, momentum is one factor, and etfdb.com recently listed more than 30 equity ETFs based on momentum.  In recent years, machine learning methods have been used extensively to find the best combination of factors.  Also, many factors have been developed recently from alternative data sources using quantitative methods, including machine-learning based sentiment analysis and image analysis.

In the past, many students in this course have not been planning on careers in investment management but instead were mainly interested in gaining more experience in quantitative methods.  The course is designed with that in mind.  We will spend time discussing machine learning methods and other data analysis topics and learn how to apply the concepts in python.  I do not expect you to be proficient in python.  The only real requirement is that you know how to open a Jupyter notebook and execute cells.

ChatGPT makes it much easier to use python. Throughout the course, we will generate python code by using ChatGPT either at the OpenAI website or via an extension to VS Code.  One skill you will develop in the course is to become a good "prompt engineer."



#### Course Schedule (by day)

1. Overview of quant investing and software tools
2. Time series models and return predictability
3. Time series models for pairs trading
4. Machine learning for classification
5. Machine learning for regression and data pipelines
6. Neural networks
7. Cross validation of hyperparameters
8. Factor models for return prediction
9. Factor models for risk prediction
10. Portfolio optimization
11. Backtesting
12. Return attribution



#### Grading

The course deliverables are weekly individual assignments and a group project.  The individual assignments involve submission of Jupyter notebooks.  They are primarily intended to ensure that everyone keeps up.  For the assignments and for the group project, googling and using ChatGPT are allowed.

The group project will involve analyzing a specific data set of signals and returns and testing a quantitative investment strategy using the methods developed in the course.  It will require putting things together, but it will not require significant new code development.  The project will be assigned the last day of class and will be due a week later.  Groups **must** consist of three or fewer students.

The individual assignments will account for half of the course grade.  The group project will account for 40%.  The remaining 10% will be based on within-group peer evaluations.

#### Data-Driven Investments Sequence

This course is a prerequisite for a full-semester spring course called *Data Driven Investments Lab.*  It will be co-taught by Kevin Crotty and myself.  The lab course will involve students working in groups to explore other data sources and to further elaborate and test strategies.  Strategies will be implemented with paper trading at Alpaca, which is a brokerage with a free python API.  

#### CQA Competition

Each year, the Chicago Quantitative Alliance (CQA) hosts a competition for universities on quantitative investing - the [CQA Challenge](https://www.cqa.org/investment_challenge).  The JGSB MBA program has a two-year winning streak in the competition, placing first in 2022 and again in 2023.  The winning JGSB teams have used machine learning methods for return prediction developed in this course and have generated higher returns than any of the 30 or so other schools in the competition.

The competition is to run a diversified long-short market-neutral portfolio with a quantitative approach.  Paper trading is done using the StockTrak platform.  Teams are judged on compliance, returns, and a video presentation of their strategy in three stages: teams that perform well on compliance proceed to the second stage, the top ten teams on compliance and portfolio returns proceed to the third stage, and teams in the third stage prepare video presentations.  

If a group participates in the CQA competition, then they can work as a group in the *Data-Driven Investments Lab* course, and the project in that course can be configured to support participation in the competition.  A team in the CQA competition is limited to five persons, but Rice can enter up to three teams.  The competition begins in the first part of November.  The start date is a little early relative to the timing of our courses, but you could use a generic strategy initially and then later trade into a strategy that you have optimized and tested.  The contest lasts until the first of April, and participation entails a commitment until then.  


#### Honor Code

The Rice University honor code applies to all work in this course.  Each student must do his or her own assignments, but it is allowed and in fact encouraged for students to seek advice from each other.  Likewise, groups must do their projects, but they can seek advice from students in other groups.  Also, searching for advice on the internet is allowed.


#### Disability Accommodations

Any student with a documented disability requiring accommodations in this course is encouraged to
contact me outside of class. All discussions will remain confidential. Any adjustments or accommodations
regarding assignments or the final exam must be made in advance. Students with disabilities
should also contact Disability Support Services in the Allen Center.



